# Generated by Django 4.0.4 on 2023-02-14 23:49

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Neurologico',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('glasgow', models.IntegerField()),
                ('pupilas', models.CharField(max_length=25)),
                ('sas', models.CharField(max_length=200)),
                ('dor', models.IntegerField()),
                ('pic', models.CharField(max_length=200)),
                ('sj02', models.IntegerField()),
                ('data_criacao', models.DateField(auto_now_add=True)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.usuario')),
            ],
        ),
    ]
