# Generated by Django 4.0.5 on 2023-02-03 15:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Neurologico',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('glasgow', models.IntegerField()),
                ('pupilas', models.CharField(max_length=25)),
                ('sas', models.CharField(max_length=200)),
                ('dor', models.IntegerField()),
                ('pic', models.CharField(max_length=200)),
                ('sj02', models.IntegerField()),
            ],
        ),
    ]
