# Generated by Django 4.0.5 on 2023-06-28 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neurologico', '0003_alter_neurologico_id_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='neurologico',
            name='abertura_ocular',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='neurologico',
            name='resposta_motora',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='neurologico',
            name='resposta_verbal',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
