# Generated by Django 4.0.5 on 2023-02-03 14:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=225)),
                ('cpf', models.CharField(max_length=11)),
                ('data_nascimento', models.DateField()),
                ('email', models.CharField(blank=True, max_length=200, null=True)),
                ('senha', models.CharField(blank=True, max_length=200, null=True)),
                ('data_criacao', models.DateField(auto_now_add=True)),
                ('perfil', models.CharField(blank=True, max_length=100, null=True)),
                ('peso', models.FloatField(default=0.0)),
                ('reg', models.CharField(blank=True, default='', max_length=100)),
                ('convenio', models.CharField(blank=True, default='', max_length=225)),
                ('leito', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
    ]
