# Generated by Django 4.0.4 on 2022-11-24 01:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
                ('cpf', models.CharField(max_length=11)),
                ('data_nascimento', models.DateField()),
                ('email', models.CharField(max_length=200)),
                ('senha', models.CharField(max_length=200)),
                ('data_criacao', models.DateField(auto_now_add=True)),
                ('perfil', models.CharField(max_length=100)),
            ],
        ),
    ]
