# Generated by Django 4.0.4 on 2023-05-29 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='st_alta',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
