# Generated by Django 4.0.4 on 2022-11-30 22:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Respiracao',
            fields=[
                ('id_dado_respiratorio', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('modo_esp', models.BooleanField()),
                ('modo_vm', models.BooleanField()),
                ('fi02', models.DecimalField(decimal_places=1, max_digits=3)),
                ('peep', models.DecimalField(decimal_places=1, max_digits=3)),
                ('p_pico', models.IntegerField()),
                ('pet_co2', models.IntegerField()),
                ('pressao_cuff', models.BooleanField()),
            ],
        ),
    ]
