# Generated by Django 4.0.5 on 2023-03-07 01:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Respiracao',
            fields=[
                ('id_dado_respiratorio', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('modo_esp', models.CharField(max_length=255)),
                ('modo_vm', models.CharField(max_length=255)),
                ('fi02', models.IntegerField()),
                ('peep', models.DecimalField(decimal_places=1, max_digits=3)),
                ('p_pico', models.DecimalField(decimal_places=1, max_digits=3)),
                ('volume_corrente', models.IntegerField()),
                ('data_criacao', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
