# Generated by Django 4.0.5 on 2023-04-28 14:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hemodinamica',
            fields=[
                ('id_dado_hemodinamica', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pressao_venosa_central', models.DecimalField(decimal_places=1, max_digits=4)),
                ('pap', models.DecimalField(decimal_places=1, max_digits=4)),
                ('poap', models.IntegerField()),
                ('ic', models.DecimalField(decimal_places=1, max_digits=4)),
                ('debito_cardiaco', models.DecimalField(decimal_places=1, max_digits=4)),
                ('sv02', models.IntegerField()),
                ('data_criacao', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
