# Generated by Django 4.0.4 on 2022-06-01 01:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SinaisVitais',
            fields=[
                ('id_sinal_vital', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('temperatura', models.DecimalField(decimal_places=2, max_digits=4)),
                ('frequencia_respiratoria', models.IntegerField()),
                ('saturacao', models.IntegerField()),
                ('frequencia_cardiaca', models.IntegerField()),
                ('pa_sistolica', models.DecimalField(decimal_places=2, max_digits=6)),
                ('pa_diastolica', models.DecimalField(decimal_places=2, max_digits=6)),
                ('pa_media', models.DecimalField(decimal_places=2, max_digits=6)),
                ('data_criacao', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
