# Generated by Django 4.0.5 on 2023-05-17 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
        ('sinaisvitais', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sinaisvitais',
            name='id_usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuario.usuario'),
        ),
    ]
