# Generated by Django 4.0.5 on 2023-06-08 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sinaisvitais', '0003_alter_sinaisvitais_id_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sinaisvitais',
            name='id_usuario',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
